package com.arise.fromtheashes.navigation

const val ROUTE_HOME="hOME"
const val ROUTE_LOGIN="login"
const val ROUTE_REGISTER="register"
const val ROUTE_Splash="splash"
const val ROUTE_ADD_PRODUCT="addproducts"
const val ROUTE_VIEW_PRODUCT="viewproducts"
const val ROUTE_UPDATE_PRODUCT="updateproducts"
const val ROUTE_VIEW_UPLOAD="view_upload"
const val ROUTE_DASHBOARD = "dashboard"
const val ROUTE_ADD_STUDENT = "students"
const val ROUTE_SPLASH = "splashscreen"
const val ROUTE_VIEW_STUDENTS = "viewproducts"
const val ROUTE_UPDATE_STUDENT = "updateclient"